### ISSUE TITLE
RobotControl.sh starting issue

### ISSUE THREAD

**Issue by bigdavisc** [googlearchive/ChromeWebLab#74]
## Whenever I try to run RobotControl.sh, this is what is says in my terminal:

Starting RobotControl (node server)

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: dlopen(/Users/bigdavisc/Documents/Google Sketchbot/ChromeWebLab-master/Sketchbots/sw/robotcontrol/src/node_modules/canvas/build/Release/canvas.node, 1): Library not loaded: /usr/local/lib/libpng16.16.dylib
  Referenced from: /Users/bigdavisc/Documents/Google Sketchbot/ChromeWebLab-master/Sketchbots/sw/robotcontrol/src/node_modules/canvas/build/Release/canvas.node
  Reason: Incompatible library version: canvas.node requires version 33.0.0 or later, but libpng16.16.dylib provides version 30.0.0
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bigdavisc/Documents/Google Sketchbot/ChromeWebLab-master/Sketchbots/sw/robotcontrol/src/node_modules/canvas/lib/bindings.js:2:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by brianhinch** [comment]
You may be missing libpng. Check that you have gone through everything in step 2 from [Installing robotcontrol](https://github.com/GoogleChrome/ChromeWebLab/tree/master/Sketchbots#installing-robotcontrol).
