### ISSUE TITLE
Error when trying run robotcontrol with MindstormsNXT

### ISSUE THREAD

**Issue by cowboyh4t** [googlearchive/ChromeWebLab#75]
I'm having problems when trying to run 

> /start_robot_control

 after set draw machine as MindstormsNXT in ConfigParams.js
`DRAW_MACHINE_TYPE: 'MindstormsNXT'`

the error is the following:

> ubuntu@ubuntu:~/LegoToTheBitch/PROJETO/Sketchbots/sw/robotcontrol$ ./start_robot_control 
> 
> /home/ubuntu/LegoToTheBitch/PROJETO/Sketchbots/sw/robotcontrol/src/node_modules/node-nxt/node-nxt.js:194
>   var wrap = function (name, class, pin, addr, handle, status, linkq) {
>                              ^^^^^
> SyntaxError: Unexpected reserved word
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Object.<anonymous> (/home/ubuntu/LegoToTheBitch/PROJETO/Sketchbots/sw/robotcontrol/src/draw_machines/MindstormsNXT/Robot3Axis.js:17:15)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)

Node v0.10.36
npm 1.4.28

Can someone help me?
thanks :)

**Comment by cowboyh4t** [comment]
I solved! you just need download node-nxt from GitHub in last version and replace all files in Sketchbots/sw/robotcontrol/src/node_modules/node-nxt.  :)

Node-NXT project: https://github.com/paulcuth/node-nxt (click in "clone or download" and "Download ZIP"), or just click [here](https://github.com/paulcuth/node-nxt/archive/master.zip).

good luck for who will try! :)
